ASOS-217 (Merge to develop/bullfrog)
ccosp/open-o pull request #134
Opened 2024-09-24 14:14 UTC by kateyang1998

- Removed ebs-client 0.0.6, and implemented the customized ebs-client classes.
- Avoided looking for XOP references in the response by setting the properties to "0".
- Fixed the header parsing error to enable the list being displayed on both Sent and Download pages.
- Fixed the signature invalid error to enable downloading the files.
- Fixed the NullPointerException error caused by SpringUtils.getBean when running MCEDT tests.

2024-09-26 00:52 UTC, yingbull requested changes
This was great work to get functional but needs some further code cleanups for adding to the branch/repo.

2024-09-26 00:52 UTC, yingbull commented on pom.xml
> +        <!-- <dependency>
If it is no longer needed, let's not encourage comment bloat; comments like these don't give any indication of why it is commented out, when it should be commented back in, etc; we can always see a deletion if we go looking in the commit logs and between the code and a good commit message we can search for that.  Please remove the code and test the removal.

2024-09-26 00:52 UTC, yingbull commented on src/main/java/org/oscarehr/integration/ebs/client/ng/DownloadInInterceptor.java
> +		// SOAPMessage soapMessage = (SOAPMessage) message;
Why is this here? when would we uncomment it? If it is really needed to stay as a comment there should be some context as to what it is and why it is commented out and when/how we would know to use it again.  Else, please remove.

2024-09-26 00:52 UTC, yingbull commented on src/main/java/org/oscarehr/integration/ebs/client/ng/EdtClientBuilder.java
> +
There are a number of formatting details like this that aren't ideal; no need for the extra lines between everything.  While we are working to get the linters to help with this in the IDE standard, just about any formatting took for java in VSCode or IntelliJ should be able to clean this up if you run them on the files.  As these are new files, make them look the best!

2024-09-26 00:52 UTC, yingbull commented on src/main/java/org/oscarehr/integration/ebs/client/ng/EdtClientBuilder.java
> +//u     requestContext.put(BindingProviderProperties.CONNECT_TIMEOUT, 1000); // Timeout in millis
Same, why have the comment -

2024-09-26 00:52 UTC, yingbull commented on src/main/java/org/oscarehr/integration/ebs/client/ng/EdtClientBuilder.java
> +
Why this space

2024-09-26 00:52 UTC, yingbull commented on src/main/java/org/oscarehr/integration/ebs/client/ng/EdtClientBuilder.java
> +        HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy(); // Line #1
What do the Line #1 etc etc comments mean? If they mean something let's comment the  block, I don't think lines mean anything here? If so, remove.   Maybe it has to do with how it was breaking down the API stuff line by line above? either way needs a better comment.

2024-09-26 00:52 UTC, yingbull commented on src/main/java/org/oscarehr/integration/ebs/client/ng/EdtClientBuilder.java
> +
Again, all sorts of formatting stuff.  

When fixing formatting you can do some of it at a time as well, even with the automated tools, per commit, but whatever works.

2024-09-26 00:52 UTC, yingbull commented on src/main/java/org/oscarehr/integration/ebs/client/ng/EdtClientBuilder.java
> +				+ " " + WSHandlerConstants.ENCRYPT; // plus decryption
Maybe can tolerate these if no other way to do it clearly, but good to avoid end of line.
I know some of this was from the original file you edited, but when we are putting in a new file, it would be good to get it clear at least in formatting even if we are being conservative with code changes.

2024-09-26 00:52 UTC, yingbull commented on src/main/java/org/oscarehr/integration/ebs/client/ng/EdtClientBuilderConfig.java
> +
Again about the formatting.  :-)

Also, not a fan of no documentation for all these methods.  I get that you didn't write them all, but I think between an AI looking over the code and you giving it some related context, and what you learned tracing this code finding the issues to verify, you should be able to QA the comments. 

If you install continue.dev and link it to the DeepSeek API I gave you, that might be one way to easily comment the methods by highlighting them and asking it to do it (also avoids any issues if you do copy and pasting for it).

2024-09-26 00:52 UTC, yingbull commented on src/main/resources/clientKeystore.properties
> +org.apache.ws.security.crypto.merlin.keystore.password=pass
Is there documentation about this / how to change it / etc somewhere?

2024-09-26 00:52 UTC, yingbull commented on src/main/resources/clientKeystore.properties
> +org.apache.ws.security.crypto.merlin.keystore.file=/var/lib/Oscar/mcedtconf.jks
Why did the file name have to change?

2024-09-26 00:52 UTC, yingbull commented on src/test/java/org/oscarehr/integration/mcedt/EDTBaseTest.java
> +            context.setConfigLocations(new String[]{"/applicationContext.xml","/applicationContextBORN.xml"});
Could you explain this? I am wondering if this was also something that was involved in aligning with conformance requirements when you did it (does BORN run through MCEDT?) - just trying to understand context.   Comments would be helpful on classes like this particularly with code additions both for the code and for context when reviewing.

2024-09-26 00:52 UTC, yingbull commented on docs/archive/mcedt/MCEDT_HCV_Issue_Knowledge.md
> +There are 18 test cases skipped, and we are not going to enable them to run at this point.
This is a good start, though maybe update a bit more about those test (skipped as they can only be testing live with the API and state of function as well is unknown.)

2024-09-26 00:52 UTC, yingbull commented on src/main/java/org/oscarehr/integration/ebs/client/ng/AttachmentCachingInterceptor.java
> +package org.oscarehr.integration.ebs.client.ng;
More on comments below, but we should have class header comments on all the classes, method comments; I would go with javadoc style if nothing else for now.  Doesn't need to be much; even if not a great comment if it comes from the AI and does not look wrong and you have nothing to add to it, it can work.

2024-09-26 00:52 UTC, yingbull commented on src/main/java/org/oscarehr/integration/ebs/client/ng/AttachmentCachingInterceptor.java
> +
This applies to all the files, but there is no license information at the start.   Was there on the others? What was there in the package you decomposed from the source, anything in the source repo on the license? As well as copyright? If it was in the root of the packages best to just add whatever is appropriate from that to the start of each file.   Feel free to post what you are thinking in the devchat for discussion.   Files with modifications done by Magenta should have an additional copyright note added 2024 and them in additional to what was there before.

2024-09-26 00:54 UTC, yingbull commented
Hi @kateyang1998 - please reach out if you have questions.  I think you can handle this fixes (let's let @gongjian1981 focus on his tasks), unless you have questions to bring up to him in devchatter about it (remember to talk as much in devchatter as we can).

2024-09-26 01:06 UTC, kateyang1998 commented
Thank you Michael, I will look into the details tomorrow after stand up. If
I have any question I will let you know on slack.

On Wed, Sep 25, 2024 at 8:54 PM yingbull ***@***.***> wrote:

> Hi @kateyang1998 <https://github.com/kateyang1998> - please reach out if
> you have questions. I think you can handle this fixes (let's let
> @gongjian1981 <https://github.com/gongjian1981> focus on his tasks),
> unless you have questions to bring up to him in devchatter about it
> (remember to talk as much in devchatter as we can).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ccosp/open-o/pull/134#issuecomment-2375522787>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDY3W2WFG2NMHIV7XW4PFWDZYNLMZAVCNFSM6AAAAABOYNKWDKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNZVGUZDENZYG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-26 14:41 UTC, kateyang1998 commented on src/main/resources/clientKeystore.properties
> +org.apache.ws.security.crypto.merlin.keystore.file=/var/lib/Oscar/mcedtconf.jks
The file name changed since we had to connect to the conformance server, the jks file's name is mcedtconf.jks.

2024-09-26 21:08 UTC, yingbull commented on src/main/resources/clientKeystore.properties
> +org.apache.ws.security.crypto.merlin.keystore.file=/var/lib/Oscar/mcedtconf.jks
OK; but while were two lines removed and only one put in?  
This could will be be for the production setup... likely best to leave it at mcedt.jks? 
Did you have to run commands to create that file?  You don't need to include the keys, but maybe allude to how this file is created (I assume the "admin" will do this with a command) once they are given settings from MOH for the MCEDT env.

2024-09-26 21:18 UTC, yingbull requested changes
Getting there!  A few more changes and class/method header block comments as per standard programming practice.

2024-09-26 21:18 UTC, yingbull commented on src/test/java/org/oscarehr/integration/mcedt/EDTBaseTest.java
>      public static void setUpBeforeClass() {
Still need method documentation added; jdoc style fine, this would be a block comment in jdoc at the start of this and all other methods. AI can help.

2024-09-26 21:18 UTC, yingbull commented on src/test/java/org/oscarehr/integration/mcedt/EDTBaseTest.java
> +            context.setConfigLocations(new String[]{"/applicationContext.xml","/applicationContextBORN.xml"});
Why is BORN involved?

2024-09-26 21:18 UTC, yingbull commented on src/main/java/org/oscarehr/integration/ebs/client/ng/EdtClientBuilder.java
>  				// swallow
Should we really just drop any exceptions here? @gongjian1981 @kateyang1998

2024-09-26 21:18 UTC, yingbull commented on src/main/java/org/oscarehr/integration/ebs/client/ng/EdtClientBuilder.java
>  public class EdtClientBuilder {
All of these classes should have javadoc documentation blocks added above them; use AI to generate, look it over, see if you agree, at least start with that.

2024-09-26 21:18 UTC, yingbull commented on src/main/java/org/oscarehr/integration/ebs/client/ng/EdtClientBuilder.java
> - * with a Timestamp element for each message TTL for the SOAP message
Let's get this stuff added into the /docs document, so all the info or at least key stuff about the process is in the documentation md file.

2024-09-27 14:00 UTC, kateyang1998 commented on src/main/resources/clientKeystore.properties
> +org.apache.ws.security.crypto.merlin.keystore.file=/var/lib/Oscar/mcedtconf.jks
I will change it back. We didn't run commands to create this file. There is a document in the docs/archive that describes how to generate the .jks file. For us, we got the JK file from Deval directly and imported it into the filepath. 
There is no impact if we change it back. We just need to import the jsk file again in the future if we need to run the mcedt functionalities (with the conformance server information).

2024-09-27 14:24 UTC, kateyang1998 commented on src/test/java/org/oscarehr/integration/mcedt/EDTBaseTest.java
> +            context.setConfigLocations(new String[]{"/applicationContext.xml","/applicationContextBORN.xml"});
I removed the "/applicationContextBORN.xml". 
This file is for configuring "bornScheduledTask" and "schedulerBorn". It is not used in the EDT tests.

2024-09-27 14:42 UTC, kateyang1998 commented on src/main/java/org/oscarehr/integration/ebs/client/ng/EdtClientBuilder.java
>  				// swallow
If the algorithmURI provided is already associated with a class (meaning it’s already registered), the method will throw this exception to avoid overwriting the previous registration or creating conflicting definitions for the same transformation.
We think it's not necessary to drop the exception here.

2024-10-05 03:03 UTC, yingbull approved these changes

2024-10-05 03:04 UTC, merged