Removed unneeded persist, remove & merge functions from ServiceReques…
ccosp/open-o pull request #55
Opened 2024-07-25 20:00 UTC by Wrekky

…tTokenDao. Added a check to manage entities in case removal function is called and entity is not currently in the entity manager.

2024-07-25 20:29 UTC, yingbull requested changes

2024-07-25 20:29 UTC, yingbull commented on src/main/java/org/oscarehr/common/dao/ServiceRequestTokenDaoImpl.java
> +        query.setParameter("token", token);//
Is the comment line needed?

2024-07-25 20:29 UTC, yingbull commented on src/main/java/org/oscarehr/common/dao/ServiceRequestTokenDao.java
> -    void remove(ServiceRequestToken token);
What's the rationale this change? How is it related to the comment on the commit? Feels like it needs to be another commit or at least another comment on the commit message?

2024-07-26 16:37 UTC, yingbull requested changes

2024-07-26 16:37 UTC, yingbull commented on src/main/java/org/oscarehr/common/dao/AbstractDaoImpl.java
> +			managedEntity = o;
I think we need a comment here to make this clearer.  What is it doing when it is managed and why?

2024-07-26 16:37 UTC, yingbull commented on src/main/java/org/oscarehr/common/dao/ServiceRequestTokenDaoImpl.java
> -    return this.entityManager.merge(token);
Is the rationale for this in Jira? Maybe a hint as to reason for the removals on commit message? I think I follow but could be clearer for others / future.

2024-07-26 17:01 UTC, Wrekky commented on src/main/java/org/oscarehr/common/dao/AbstractDaoImpl.java
> +			managedEntity = o;
I'll add a comment after I get the email issue fixed.

2024-07-26 17:01 UTC, Wrekky commented on src/main/java/org/oscarehr/common/dao/ServiceRequestTokenDaoImpl.java
> -    return this.entityManager.merge(token);
yeahhh you're right, ill add some info about this on the jira ticket and add a comment on removing it in the commit message. This is making it match previous behavior. These functions were previously being called in AbstractDao which this class already extends.

2024-07-29 16:17 UTC, closed without merging