Asos 103 skipped unit test cleanup
ccosp/open-o pull request #64
Opened 2024-07-26 19:04 UTC by ayushkaneria

Resolved all UnitTests that was Ignored because of Failure or Errors.

2024-07-26 19:23 UTC, yingbull requested changes

2024-07-26 19:23 UTC, yingbull commented on src/test/java/org/oscarehr/common/dao/BedCheckTimeDaoTest.java
> +		String expectedResult = "select bct from BedCheckTime bct where bct.programId = ? order by bct.time asc";
Why was this set this way? Feels like a comment needed?

2024-07-26 19:23 UTC, yingbull commented on src/test/java/org/oscarehr/common/dao/BillingPaymentTypeDaoTest.java
> +	@Test //Skipping until issue is resolved
Is this comment still valid?

2024-07-26 19:23 UTC, yingbull commented on src/test/java/org/oscarehr/common/dao/DemographicExtDaoTest.java
> +	// demographicExt table has a UNIQUE KEY constraint `uk_demo_ext` on columns `demographic_no` and `key_val`
Why is all this commented out? When would it be uncommented and why?

2024-07-26 19:23 UTC, yingbull commented on src/test/java/org/oscarehr/common/dao/StudyDataDaoTest.java
> +		studyData1.setDeleted(false);
What's with the false? Feels like this method needs comments

2024-07-26 19:23 UTC, yingbull commented on src/test/java/org/oscarehr/common/dao/utils/SchemaUtils.java
> +			// Drop foreign key constraints associated with tableName_maventest
Why?

2024-07-26 19:23 UTC, yingbull commented on src/test/java/org/oscarehr/common/dao/utils/SchemaUtils.java
> -				s.executeUpdate("drop table if exists " + tableName);
Why? Comments

2024-07-26 19:23 UTC, yingbull commented on src/test/java/org/oscarehr/common/dao/utils/SchemaUtils.java
> +			// Disable foreign key checks
Why comments etc - what it does we can see, why something is done is the reason to comment

2024-07-26 19:23 UTC, yingbull commented on src/test/java/org/oscarehr/research/eaaps/EaapsHandlerTest.java
> +// This Test will be removed under ASOS-188 - Dead code removals of Eaaps
Just pull the code here - we can remove the test here and do the running system code layer

2024-07-26 19:23 UTC, yingbull commented on src/test/java/org/oscarehr/research/eaaps/EaapsIntegrationTest.java
> +		assertEquals("19831223", hash.getKey());
Why?

2024-07-26 19:35 UTC, ayushkaneria commented on src/test/java/org/oscarehr/common/dao/BillingPaymentTypeDaoTest.java
> +	@Test //Skipping until issue is resolved
Nope. It was by mistake. Removing it in next commit.

2024-07-29 19:33 UTC, ayushkaneria reviewed
Update request changes

2024-07-29 19:45 UTC, yingbull commented on src/test/java/org/oscarehr/common/dao/BedCheckTimeDaoTest.java
> +		String expectedResult = "select bct from BedCheckTime bct where bct.programId = ? order by bct.time asc";
was something about this added in a comment?

2024-07-29 19:56 UTC, ayushkaneria commented on src/test/java/org/oscarehr/common/dao/BedCheckTimeDaoTest.java
> +		String expectedResult = "select bct from BedCheckTime bct where bct.programId = ? order by bct.time asc";
Yes updated.

2024-07-29 19:56 UTC, closed without merging